settings:
# input
    directory: '23_07_15'
    filename: ['COLO320DM_coverslip_48hr_mCherry_375ul_Lipofectamine_MYCgreen_mCherry568_Ki67647_Lng_LVCC.lif']
# scaling
    convert_16_to_8bit: False
    scale_image: True
    auto_scale: False
    # if auto_scale = False, set the following for each channel:
    min: [0,0,0,0]
    max: [65535,10000,65535,40000]
# z_plane
    z_stack: True
    # if z_stack = True, set one of the following to True:
    find_best_z_plane: False
    max_projection: True
    # if max_projection = True, choose whether to auto slice (only keeps slices with "high" laplacian variance)
    auto_slice: False # don't set to true yet - still in progress
    # if max_projection = True and auto_slice = False, then manually select slices to keep for all slices, set start_slice to 0 and end_slice to 'end':
    start_slice: 0
    end_slice: 'end'
# output
    return_composite: False
    # if return_composite = True, set the channel output order:
    channel_order: ['red', 'blue', 'green']
    return_channels: True
    output_file_type: '.png'

# this is for save_lif_as_tif
# only accepts 16bit and 8bit images
# iterates through each image (and each mosaic tile of the image, each time of timelapse) and returns either composites (first 3 channels only in RGB) or individual channels
# input filename should be written as a string that ends in '.lif', eg 'file.lif' or a list of strings that end in '.lif', eg ['file1.lif', 'file2.lif', 'file3.lif']
# to input every '.lif' file in the directory, set filename to the magic word 'ALL'
# return_composite only handles up to 3 channels currently
# channel_order: if returning composite image, assign a color (red, green or blue) to each channel in order
# can change '.tif' to other extensions, such as '.png', '.jpg', etc
# if output in 16bit, will output in raw only
# if scale_image: True, then output will be scaled; otherwise, returns raw images
#   if auto_scale: True, images will be scaled based on higher intensity pixel of each channel of each image (normalization)
#   if auto_scale: False, then will scale based on provided scale factors min and max (one for each channel, separated by comma)
#       for ecSeg, 8 bit, try DAPI max=60 [ (FISH channel max=30)
